#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════
# NEURO-LITE v1.0 — Master Installer
# Idempotent · Fail-fast · Colored logging
# Revised: Auto-handle missing config.env
# ═══════════════════════════════════════════════════════════
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export NEURO_ROOT="${SCRIPT_DIR}"

# ── Colors ────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

log_info()  { echo -e "${BLUE}[INFO]${NC}  $(date '+%H:%M:%S') $*"; }
log_ok()    { echo -e "${GREEN}[  OK]${NC}  $(date '+%H:%M:%S') $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $(date '+%H:%M:%S') $*"; }
log_err()   { echo -e "${RED}[ ERR]${NC}  $(date '+%H:%M:%S') $*"; }
log_step()  { echo -e "\n${CYAN}${BOLD}══════ $* ══════${NC}"; }

export -f log_info log_ok log_warn log_err log_step
export RED GREEN YELLOW BLUE CYAN BOLD NC

# ── Pre-flight checks ────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
    log_err "This installer must be run as root (use sudo)."
    exit 1
fi

REAL_USER="${SUDO_USER:-$(whoami)}"
export REAL_USER

# ── Config Environment Handler (REVISED) ─────────────────────────
CONFIG_FILE="${NEURO_ROOT}/config.env"
REPO_CONFIG_URL="https://raw.githubusercontent.com/boybarley/NEURO-LITE-ECOSYSTEM-3/main/config.env"

if [[ ! -f "${CONFIG_FILE}" ]]; then
    log_warn "config.env not found at ${CONFIG_FILE}"
    
    # 1. Coba unduh dari GitHub
    log_info "Attempting to download config.env from repository..."
    if wget -q -O "${CONFIG_FILE}" "${REPO_CONFIG_URL}"; then
        # Cek apakah file kosong (terkadang 404 menghasilkan file kosong)
        if [[ -s "${CONFIG_FILE}" ]]; then
            log_ok "Successfully downloaded config.env from GitHub."
        else
            log_warn "Downloaded file is empty. Removing and creating default..."
            rm -f "${CONFIG_FILE}"
        fi
    else
        log_warn "Download failed."
    fi

    # 2. Jika masih tidak ada (gagal download/empty), buat default
    if [[ ! -f "${CONFIG_FILE}" ]]; then
        log_info "Creating a default config.env file..."
        cat <<EOF > "${CONFIG_FILE}"
# NEURO-LITE Default Configuration
# Auto-generated by install.sh

# Port untuk aplikasi
NEURO_LITE_PORT=8080

# Tambahkan konfigurasi lainnya di sini
EOF
        log_ok "Default config.env created at ${CONFIG_FILE}"
    fi
fi

# Source config file
source "${CONFIG_FILE}"

# Validasi variabel penting (opsional, untuk memastikan NEURO_LITE_PORT ada)
if [[ -z "${NEURO_LITE_PORT:-}" ]]; then
    log_warn "NEURO_LITE_PORT not set in config.env, defaulting to 8080"
    export NEURO_LITE_PORT=8080
fi

TOTAL_RAM_KB=$(grep MemTotal /proc/meminfo | awk '{print $2}')
TOTAL_RAM_MB=$((TOTAL_RAM_KB / 1024))
log_info "Detected RAM: ${TOTAL_RAM_MB} MB"

if [[ ${TOTAL_RAM_MB} -lt 3500 ]]; then
    log_warn "System has less than 3.5GB RAM. Performance may be degraded."
fi

# ── Create directories ───────────────────────────────────
mkdir -p "${NEURO_ROOT}/models"
mkdir -p "${NEURO_ROOT}/data"
mkdir -p "${NEURO_ROOT}/logs"
chown -R "${REAL_USER}:${REAL_USER}" "${NEURO_ROOT}/models" "${NEURO_ROOT}/data" "${NEURO_ROOT}/logs"

# ── Execute modules sequentially ─────────────────────────
MODULES_DIR="${NEURO_ROOT}/modules"
MODULES=(
    "01_os_tuning.sh"
    "02_install_deps.sh"
    "03_download_model.sh"
    "04_setup_service.sh"
)

FAILED=0
for module in "${MODULES[@]}"; do
    MODULE_PATH="${MODULES_DIR}/${module}"
    if [[ ! -f "${MODULE_PATH}" ]]; then
        log_err "Module not found: ${MODULE_PATH}"
        FAILED=1
        break
    fi

    log_step "Running ${module}"
    chmod +x "${MODULE_PATH}"

    if bash "${MODULE_PATH}"; then
        log_ok "${module} completed successfully."
    else
        log_err "${module} FAILED with exit code $?."
        FAILED=1
        break
    fi
done

if [[ ${FAILED} -eq 1 ]]; then
    log_err "Installation aborted due to failure."
    exit 1
fi

echo ""
echo -e "${GREEN}${BOLD}═══════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}${BOLD}  NEURO-LITE v1.0 installed successfully!${NC}"
echo -e "${GREEN}${BOLD}═══════════════════════════════════════════════════════${NC}"
echo -e "  Chat UI:   ${CYAN}http://localhost:${NEURO_LITE_PORT}/${NC}"
echo -e "  Admin UI:  ${CYAN}http://localhost:${NEURO_LITE_PORT}/admin${NC}"
echo -e "  Service:   ${CYAN}sudo systemctl status neurolite${NC}"
echo ""
